(setq ad-redefinition-action 'accept)   ;不要烦人的 redefine warning
(tool-bar-mode -1)                      ;禁用工具栏
(scroll-bar-mode -1)                    ;禁用滚动条
(setq inhibit-splash-screen 1)          ;; 关闭启动帮助画面
(global-hl-line-mode 1)                 ;;高亮当前行
(setq auto-save-default nil)            ;;关闭自动生成备份文件
(setq make-backup-files nil)            ;;关闭自动生成备份文件~后缀文件
(global-auto-revert-mode 1)             ;;自动加载外部修改的文件
(fset 'yes-or-no-p 'y-or-n-p)           ;;为YES/NO取别名Y/N
(setq-default cursor-type 'bar)         ;;设置全局光标样式
(setq ring-bell-function 'ignore)       ;;关闭响铃
;;设置frame的标题
(setq frame-title-format
      '("" " Watcher - "
        (:eval (if (buffer-file-name)
                   (abbreviate-file-name (buffer-file-name)) "%b"))))

;;设置字体
;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
(set-face-attribute
 'default nil
 :font (font-spec :name "-outline-Consolas-bold-italic-normal-mono-*-*-*-*-c-*-iso10646-1"
                  :weight 'normal
                  :slant 'normal
                  :size 12.5))
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font
   (frame-parameter nil 'font)
   charset
   (font-spec :name "-outline-微软雅黑-normal-normal-normal-sans-*-*-*-*-p-*-iso10646-1"
              :weight 'normal
              :slant 'normal
              :size 15.0)))

;;启动自动全屏
(defun maximize-frame ()
  "Maximizes the active frame in Windows"
  (interactive)
  ;; Send a `WM_SYSCOMMAND' message to the active frame with the
  ;; `SC_MAXIMIZE' parameter.
  (when (eq system-type 'windows-nt)
    (w32-send-sys-command 61488)))
(add-hook 'window-setup-hook 'maximize-frame t)

(provide 'init-startup)








































